services:
  db:
    image: postgres:16
    container_name: devinci-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: devinci-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      ADMIN_T_NANE: t_adam_si
      ADMIN_NAME: adam sin
      ADMIN_PASSWORD: sinale1234
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: uv run uvicorn src.app:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    container_name: devinci-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_PROXY_TARGET: http://devinci-backend:8000
    command: npm run dev -- --host 0.0.0.0

volumes:
  pgdata:
